stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py /data/interim/merged_raw_data.csv
    deps:
    - data\interim\merged_raw_data.csv
    - .\src\data\make_dataset.py
  build_features:
    cmd: python .\src\features\build_features.py /data/interim/merged_raw_data.csv
      /data/processed/processed_raw_data.csv
    deps:
    - data\interim\merged_raw_data.csv
    - data\processed\processed_raw_data.csv
    - .\src\features\build_features.py
  train_model:
    cmd: python .\src\models\train_model.py /data/processed/processed_raw_data.csv
    deps:
    - data\processed\processed_raw_data.csv
    - .\src\models\train_model.py
    params:
    - make_dataset.test_split
    - make_dataset.seed

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
